### PR TITLE
better C++

### PR DESCRIPTION
**Pull request by ncm**
This version seems to be rather a lot faster.

### CODE REVIEW

**Comment by benhoyt** [comment]
Thanks. However, note that `optimized.cpp` has already been updated a couple of times. Is this version faster than what's there now? (I'd be a bit surprised.)

**Comment by ncm** [comment]
Eh, looks about the same.

But no need for std::ios::sync_with_stdio().

**Comment by ncm** [comment]
BTW, unnecessarily-postfix op++ is non-idiomatic C++.

**Comment by ncm** [comment]
When I cloned a few minutes ago, I got one version, but when I look on github.com/benhoyt, I see a different version. Maybe you had better measure on your hardware and see.

**Comment by benhoyt** [comment]
Just checked, and this version takes ~1.6 seconds, whereas the existing master version takes ~0.46 seconds, so what we have now is a clear win. I did update the increment from `C++` to `++C`, though. :-) https://github.com/benhoyt/countwords/commit/61892e190608a2bae4f3c525417a45b8595c2af0

**Comment by ncm** [comment]
I have no clue how you got it to run so slow.

**Pull request closed without merging**
