### PR TITLE
Bash round two

### PR DESCRIPTION
**Pull request by lollipopman**
This drops the runtime from ~27s to ~17s in my local testing, thanks!

### CODE REVIEW

**Comment by akinomyoga** [comment]
Thank you for the mention!

Instead of including @akinomyoga in the commit title, maybe you could actually add [a `Co-authored-by` header](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) at the end of the commit message (You can edit the commit message by e.g. `git commit --amend` and force push by `git push -f`).

```
Co-authored-by: Koichi Murase <myoga.murase@gmail.com>
```

Maybe you can also mention the mailing list archive in the commit message:

```
https://lists.gnu.org/archive/html/help-bash/2021-03/threads.html#00198
```

**Comment by lollipopman** [comment]
> Thank you for the mention!
> 
> Instead of including @akinomyoga in the commit title, maybe you could actually add [a `Co-authored-by` header](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) at the end of the commit message (You can edit the commit message by e.g. `git commit --amend` and force push by `git push -f`).
> 
> ```
> Co-authored-by: Koichi Murase <myoga.murase@gmail.com>
> ```
> 
> Maybe you can also mention the mailing list archive in the commit message:
> 
> ```
> https://lists.gnu.org/archive/html/help-bash/2021-03/threads.html#00198
> ```

great suggestions, done!

**Comment by benhoyt** [comment]
Thanks for the contribution. On my system (Ubuntu 20.04 with bash 5.0.17) I get the following error:

```
./optimized.bash: line 20: ${b@L}${l@L}: bad substitution
```

I'm still not sure I'll include this in the benchmarks. It's still quite slow, and using bash for this seems a bit arcane (though admittedly using Forth for it is too!). I can merge it once the above is fixed, though!

**Comment by lollipopman** [comment]
> Thanks for the contribution. On my system (Ubuntu 20.04 with bash 5.0.17) I get the following error:
> 
> ```
> ./optimized.bash: line 20: ${b@L}${l@L}: bad substitution
> ```
> 
> I'm still not sure I'll include this in the benchmarks. It's still quite slow, and using bash for this seems a bit arcane (though admittedly using Forth for it is too!). I can merge it once the above is fixed, though!

Oops, sorry `${parm@L}` is a new feature in bash 5.1, I have substituted with `${param,,}` as an alternative, thanks again!

**Comment by benhoyt** [comment]
Sure, I'll merge this. It's somewhat faster on my machine too, though you must have a significantly faster processor than I -- it still takes over 2 minutes. :-)

**Pull request merged**
