### PR TITLE
Add simple janet implementation.

### PR DESCRIPTION
**Pull request by staydecent**
Saw the article and took this as a chance to write my first Janet program. Actually, this may be my first lisp-flavored program. Anyway, it's quite slow and could probably be improved a bunch.

On my laptop:
```
Timing Perl 2.09 0.00
Timing JavaScript 2.79 1.69
Timing Janet 14.24 0.00
```

I also couldn't get the Janet build tool to do anything, so wasn't able to test a compiled executable. At the very least, I hope this PR prompts someone to provide a better Janet implementation 😅

### CODE REVIEW

**Comment by benhoyt** [comment]
Thanks for the contribution. I know it's a bit arbitrary, but I hadn't heard of Janet, so I wonder if it's worth including. On the other hand, it'd be interesting to have a Lisp variant. If this is your first Janet program, maybe I will leave this open and wait to see if someone else contributes, as I would kinda like the simple variants to be idiomatic in that language (though maybe your first program is!).

**Comment by Tracnac** [comment]
Hi,

Just for fun same approach here (I'm not a cador of Janet...) and roughly the same execution time without sorting, we need a Janet expert :)

Yvan

_Updated with the sort part and missed the empty word..._

Still nothing sexy...
Exec time 9.5s avg
(Python3: 3s, Go: 1.4s, Nim:0.9s)

```
(defn main [&]

(var count-words @{})

(loop [line :iterate (file/read stdin :line)]
  (def words (string/split " " (string/ascii-lower (string/trim line))))
  (each word words
    (when (> (length word) 0) (put count-words word (+ 1 (or (get count-words word) 0))))))
(def ordered (sorted (pairs count-words)(fn [[_ v1][_ v2]](> v1 v2))))
(each [word count] ordered (print word " " count)))
```

**Comment by Tracnac** [comment]
> I also couldn't get the Janet build tool to do anything, so wasn't able to test a compiled executable. At the very least, I hope this PR prompts someone to provide a better Janet implementation 😅

The purpose of compiling via jpm is not really for the performance but for simplifying the installation of your binaries...

Yvan

if you want to try:

```shell
~/Devel/Janet/hello master +3 !4 ?21 ❯ pwd                                                                                 22:24:54
/Users/tracnac/Devel/Janet/hello
~/Devel/Janet/hello master +3 !4 ?21 ❯ cat project.janet                                                                   22:24:59
(declare-project
  :name "Hello"
  :description "Hello project"
  :dependencies [""])

(declare-executable
 :name "hello"
 :entry "main.janet")
~/Devel/Janet/hello master +3 !4 ?21 ❯ cat main.janet                                                                      22:25:03
(defn main [&]
 (print "Coucou le hibou"))
~/Devel/Janet/hello master +3 !4 ?21 ❯ jpm build                                                                           22:25:06
generating executable c source...
compiling build/hello.c to build/build___hello.o...
linking build/hello...
~/Devel/Janet/hello master +3 !4 ?21 ❯ ./build/hello                                                                       22:25:10
Coucou le hibou
~/Devel/Janet/hello master +3 !4 ?21 ❯                                                                                     22:25:15
```

**Comment by svercl** [comment]
Not an expert in Janet, but I came up with this version using a thick loop.

Edited: Apply `string/trim` like Tracnac.

```
(var counts @{})

(loop [line :iterate (file/read stdin :line)
       :let [line-trimmed (string/trim line)
             line-lower (string/ascii-lower line-trimmed)
             words (string/split " " line-lower)]
       word :in words :when (> (length word) 0)]
  (update counts word |(inc (or $ 0))))

(def ordered
  (sorted (pairs counts) (fn [[_ a-count] [_ b-count]] (> a-count b-count))))

(each [word count] ordered
  (printf "%V %V" word count))
```

**Comment by Tracnac** [comment]
The result of the 3 posted version:

Tracnac: 9.624s
staydecent: 26.808s
bradms: 22.625s

```shell
~/Devel/Janet/countwords master !1 ?6 ❯ for version in tracnac staydecent bradms ; do rm output.txt ; echo ${version} ; time janet ${version}.janet < kjvbible_x10.txt | python3 normalize.py > output.txt ; git diff --exit-code output.txt ; echo ; done
tracnac
janet ${version}.janet < kjvbible_x10.txt  9.54s user 0.07s system 99% cpu 9.624 total
python3 normalize.py > output.txt  0.11s user 0.02s system 1% cpu 9.651 total

staydecent
janet ${version}.janet < kjvbible_x10.txt  26.67s user 0.12s system 99% cpu 26.808 total
python3 normalize.py > output.txt  0.11s user 0.02s system 0% cpu 26.833 total

bradms
janet ${version}.janet < kjvbible_x10.txt  22.49s user 0.10s system 99% cpu 22.625 total
python3 normalize.py > output.txt  0.11s user 0.02s system 0% cpu 22.649 total

~/Devel/Janet/countwords master !1 ?6 ❯
```

**Comment by svercl** [comment]
Tracnac, bravo! Yours is incredibly quick on my computer clocking in at 2.6s vs mine at 4.5s. YMMV

**Comment by Tracnac** [comment]
> Trecnac, bravo! Yours is incredibly quick on my computer clocking in at 2.6s vs mine at 4.5s. YMMV

Thank you. Remind me that I have a slow computer :)
I asked help from the Janet community, pretty sure that they can do better...

Yvan

PS : I merged your super-powered loop with my table update but no better perf...

**Comment by svercl** [comment]
They should be functionally equivalent, I work from my phone a lot and need all the horizontal space I can get so I avoid nesting. I'm hoping someone from Janet community can speed this up! It's already pretty impressive as is for an interpreted language. I tried this problem using Racket and it took 10s. :/

**Comment by yumaikas** [comment]
I would have thought that Racket would be faster, at least if you gave it enough memory... Interesting.

I wonder if any of the compiled common lisps do well here?

**Comment by svercl** [comment]
Would love to see a CL version. I would think Racket would be quicker too, it's using Chez now. Maybe my code just isn't the brightest. You can see it under my fork under the racket branch.

**Comment by svercl** [comment]
Quickly threw this together in Common Lisp, it's not correct (yet) but it's getting there. Feel free to use this for inspiration. Common Lisp does not have a function built-in to split sequences, so I used ASDF/UIOP for that. 

Edit: phones are hard
Edit: a word

```
(require :asdf)

(defparameter *counter* (make-hash-table :test #'equal))
(defconstant +spaces+ '(#\Space #\Tab #\Newline))

(defun update-word (word)
  (let ((current (gethash word *counter* 0)))
    (setf (gethash word *counter*) (1+ current))))

(loop for line = (read-line nil nil) while line
      for line-trimmed = (string-trim +spaces+ line)
      for line-lower = (string-downcase line-trimmed)
      for words = (uiop:split-string line-lower)
      do (loop for word in words when word do (update-word word)))

(let ((ordered (loop for key being the hash-keys of *counter*
                     using (hash-value value)
                     collect (cons key value))))
  (sort ordered #'> :key #'cdr)
  (dolist (val ordered)
    (format t "~a ~a~%" (car val) (cdr val))))
```

**Comment by bakpakin** [comment]
Here is a janet version that uses a chunking mechanism (mostly copied from Janet's gitter chat):

```
(def splitter (peg/compile '(* :s* (any (* :s* '(some :S))) ':s*)))
(def freqs @{})
(def buf @"")
(def buf-size (* 64 1024))

(forever
  (:read stdin buf-size buf)
  (if (empty? buf) (break))
  (def words (peg/match splitter (string/ascii-lower buf)))
  (buffer/clear buf)
  (def trailing-ws (array/pop words))
  (if (= trailing-ws "")
    (unless (empty? words) (buffer/push buf (array/pop words)))
    (buffer/push buf trailing-ws))
  (each word words
    (if-let [c (get freqs word)]
      (put freqs word (+ 1 c))
      (put freqs word 1))))

(each [k v] (reverse! (sort-by 1 (pairs freqs)))
  (print k " " v))
```

**Comment by benhoyt** [comment]
I'd definitely sooner see a Common Lisp or Scheme version, as those (seem to me) are more well known. Common Lisp is also quite fast from what I here. Any takers for a Common Lisp edition? (simple and/or optimized)

**Comment by svercl** [comment]
Ben, I posted an early WIP version in Common Lisp above. It needs a little loving, but it's almost complete. Furthermore, which implementation of Scheme would be acceptable? Many of them do not include a hash table in their "standard library".

**Comment by uvtc** [comment]
@benhoyt , for reference:

  * [Janet homepage](https://janet-lang.org/)
  * [on github](https://github.com/janet-lang/janet)
  * [Janet community docs site](https://janetdocs.com/), with
  * [online "Playground"](https://janetdocs.com/playground)
  * [Awesome Janet list](https://github.com/ahungry/awesome-janet)

And it has active gitter channels and a discussion forum. It's actively developed and a pleasure to use.

**Comment by benhoyt** [comment]
Thanks. @bradms Care to submit a separate PR with a working Common Lisp version,  with how to run it and benchmark it in test.sh / benchmark.py?

**Comment by svercl** [comment]
Funnily enough there's an example of word frequency in the Scheme Programming Language book [here](https://www.scheme.com/tspl4/examples.html#./examples:h4)

**Comment by svercl** [comment]
@benhoyt I will be submitting a PR once I have it working properly. Unless someone beats me to the punch. ;)

**Comment by svercl** [comment]
@yumaikas  there's some smart people over at [racket-users](https://groups.google.com/g/racket-users/c/lGA60P6jboY) which got a very fast version in Racket

**Comment by benhoyt** [comment]
I'm going to close this one due to lack of response, and I'm not sure I'd include Janet in any case. We do at least have Common Lisp now.

**Comment by Tracnac** [comment]
Hi Ben,
You have all answer that you need in this PR (simple by @Tracnac and optimised by @bakpakin), bytheway you're not interested by a Janet version and you are the king of this repo, it's your right.
Common Lisp and Janet share nothing except maybe parenthesis...
Yvan

**Comment by uvtc** [comment]
@benhoyt , here's the "simple" @Tracnac version lightly formatted with a few more spaces and newlines for readability:

~~~clojure
(defn main
  [&]
  (var count-words @{})
  (loop [line :iterate (file/read stdin :line)]
    (def words (string/split " " (string/ascii-lower (string/trim line))))
    (each word words
      (when (> (length word) 0)
        (put count-words
             word
             (+ 1 (or (get count-words word) 0))))))
  (def ordered (sorted (pairs count-words)
                       (fn [[_ v1] [_ v2]]
                         (> v1 v2))))
  (each [word count] ordered
    (print word " " count)))
~~~

On my system, comparing @Tracnac 's version (above) and @bakpakin 's optimized version, I find bakpakin's to be quite a bit faster.

**Pull request closed without merging**
