### PR TITLE
 patched simple ocaml version

### PR DESCRIPTION
**Pull request by pkhry**

### CODE REVIEW

**Comment by benhoyt** [comment]
This looks a bit more complex, so I'm not about updating `simple.ml`. Is this faster? In that case, what about adding it as `optimized.ml`?

**Comment by pkhry** [comment]
no, its not optimized, just uses functorial interface on hashtable and doesn't use polymorphic comparison. It may be a tad bit faster. If it doesn't fit as simple.ml implementation then feel free to close the request.

**Comment by mseri** [comment]
@benhoyt the specialized hash table used in this version is more verbose but also idiomatic than the previous one (and is also recommended by the stdlib documentation: the polymorphic one that was used previously is known to have many collisions).

Similarly, the use of imperative while loop (which may not do much difference here though) is a very common approach, usually recommended for fast looping due to fewer chances to allocate.

If you ask anybody in the community this would be considered a simple and immediate solution.

**Comment by benhoyt** [comment]
Great, thanks -- will merge

**Pull request merged**
