### PR TITLE
Further optimize Go implementation (~ 10% improvement)

### PR DESCRIPTION
**Pull request by kevburnsjr**
This updated `optimized.go` is about 10% more efficient than the existing implementation.

- Reduce system calls using buffered output writer
- Reduce allocations by replacing `int` pointer with `struct` pointer
- Reduce data copying by removing `word` buffer, performing lowercase transformation against read buffer directly

### CODE REVIEW

**Comment by kevburnsjr** [comment]
## Before
```
> time ./optimized-go <kjvbible_x10.txt > out.txt

real    0m1.385s
user    0m1.304s
sys     0m0.087s
```
## After
```
> time ./optimized-go <kjvbible_x10.txt > out.txt

real    0m1.225s
user    0m1.215s
sys     0m0.019s
```

**Comment by benhoyt** [comment]
Thanks! On my testing I get about a 4.5% improvement (I'm running under benchmark.py so it does 5 runs and takes the min time -- this also outputs to `>/dev/null`, same as all the other benchmarks). I was curious which of the optimizations is actually helping most, and I get *all* of the improvement from just the `bufio` outputting change. In my tests the other two changes don't actually help a noticeable amount. Is this the case for you too?

**Comment by kevburnsjr** [comment]
@benhoyt It makes sense that the total reduction would appear less when running normalize since its virtually constant execution time dilutes the performance improvements. I did notice an improvement from the other changes. 🤷‍♂️

**Comment by benhoyt** [comment]
Thanks again @kevburnsjr. I'm going to leave the repo and blog entry stand as is, but I do think the bufio outputting change is a good one.

**Pull request closed without merging**
