### PR TITLE
Added Dart version

### PR DESCRIPTION
**Pull request by Doaxan**
> Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "linux_x64"

Language      | Simple | Optimized | Notes
------------- | ------ | --------- | -----
`grep`        |   0.05 |      0.05 | `grep` baseline; optimized sets `LC_ALL=C`
`wc -w`       |   0.26 |      0.34 | `wc` baseline; optimized sets `LC_ALL=C`
Perl          |   2.09 |           | by Charles Randall
Python        |   2.68 |      1.53 | 
JavaScript    |   2.93 |      1.67 | by Dani Biro
AWK           |   4.06 |      0.00 | optimized uses `mawk`
Shell         |  16.13 |      1.97 | optimized does `LC_ALL=C sort -S 2G`
Dart          |  37.48 |      2.14 | by Amir Fazleev

### CODE REVIEW

**Comment by Doaxan** [comment]
Also, if you are interested, you can compile a binary version:
> $ dart compile exe optimized.dart
>

**Comment by benhoyt** [comment]
Thanks for the contribution! Unfortunately the `simple.dart` version takes a *very* long time (I think I waited to 60s and it still wasn't done, save I gave up). Is there something wrong with it, such as unbuffered stdin? I tried it on the file 1/10th the size (plain `kjvbible.txt`) and it takes ~9 seconds on that one. Any ideas?

**Comment by Doaxan** [comment]
I tried several times to rewrite this simple version, but my attempts were unsuccessful. ~37s on my i7-3610qm is minimum for all code variations, including "readByteSync". Can go deeper into this question, but this will no longer be the simple version :smile: 

https://github.com/dart-lang/sdk/issues/45255

**Comment by benhoyt** [comment]
Yeah, I don't think we can include it until we figure out and address that huge time for simple.dart, as currently it just makes Dart look really really slow. :-) Going to leave open for a while to see if others have suggestions.

**Comment by benhoyt** [comment]
Going to close this now due to lack of action.

**Pull request closed without merging**
