### PR TITLE
simple implementation for Crystal language

### PR DESCRIPTION
**Pull request by ilmanzo**
simple implementation using the [Crystal programming language](https://crystal-lang.org/)
on my pc, this outperforms the optimized Go :)

### CODE REVIEW

**Comment by roscrl** [comment]
Are you running on Linux/MacOS ?

Getting pretty poor performance using WSL2 on my machine at the moment

Language      | Simple | Optimized | Notes
------------- | ------ | --------- | -----
`grep`        |   0.03 |      0.03 | `grep` reference; optimized sets `LC_ALL=C`
`wc -w`       |   0.20 |      0.16 | `wc` reference; optimized sets `LC_ALL=C`
Go            |   1.04 |      0.34 | 
Python        |   1.86 |      1.11 | 
Ruby          |   2.99 |           | 
Crystal       |   6.94 |           | simple implementation

**Comment by benhoyt** [comment]
Thanks for the contribution - merging!

**Comment by ilmanzo** [comment]
thanks for merging.

Yes, on my linux system I have somewhat better results than simple Go , but I guess is mainly due to I/O performance. Be sure to have an up-to-date crystal installation.  

```
Language      | Simple | Optimized | Notes
------------- | ------ | --------- | -----
Forth         |   0.00 |      0.00 | 
C#            |   0.00 |           | original by John Taylor
`grep`        |   0.04 |      0.04 | `grep` reference; optimized sets `LC_ALL=C`
`wc -w`       |   0.24 |      0.31 | `wc` reference; optimized sets `LC_ALL=C`
C             |   0.93 |      0.20 | 
Crystal       |   1.12 |           | simple implementation
Go            |   1.16 |      0.36 | 
Rust B        |   1.49 |      0.29 | also by Andrew: bonus and custom hash
Rust A        |   1.58 |      0.37 | by Andrew Gallant
C++           |   1.67 |      0.96 | "optimized" isn't very optimized
Python        |   2.01 |      1.21 | 
AWK           |   3.25 |      1.02 | optimized uses `mawk`
Shell         |  13.01 |      1.68 | optimized does `LC_ALL=C sort -S 2G`
```

**Comment by roscrl** [comment]
Whoops! I never built with --release flag, getting timings closer to yourself now.

**Pull request merged**
