### PR TITLE
WIP: Add simple Racket version

### PR DESCRIPTION
**Pull request by svercl**
May not be the best code, just wanted more Lisp in here. Help is definitely wanted to improve this.

### CODE REVIEW

**Comment by benhoyt** [comment]
Thanks for the contribution! However, this takes 12-13 seconds to run on my setup, so it's very slow. Is the input being buffered, or is there something else wrong here? Or is Racket just very slow. I'm disinclined to include it as is, as it just makes Racket look very slow (though maybe that's accurate!).

**Comment by benhoyt** [comment]
Or I could do what I've done with Bash (takes 2+ minutes!) and merge the code but not include it in the benchmarks?

**Comment by svercl** [comment]
I'm a little confused by the performance as well! It takes roughly the same time on my desktop computer. I'll admit Racket is not my lisp-like language of choice. This could definitely be improved.

**Comment by svercl** [comment]
I wouldn't merge this yet until the performance is resolved.

**Comment by svercl** [comment]
I did a little cleaning up, but still takes a long time. I opted not to include it in the benchmarks.

**Comment by benhoyt** [comment]
Sounds good -- thanks for your contribution! (Added credits to README anyway)

**Pull request closed without merging**
