### PR TITLE
Update simple.cs

### PR DESCRIPTION
**Pull request by akraines**
Use StringComparer.OrdinalIgnoreCase to avoid needing to call ToLower on every line

### CODE REVIEW

**Comment by euantorano** [comment]
Note: I tried this change and while it works, it does mean that the output is different to all other implementations - this causes `test.sh` to fail.

**Comment by akraines** [comment]
you can call to lower on output - it is still doing less work

**Comment by akraines** [comment]
Did it improve the bentchmark?

**Comment by benhoyt** [comment]
Yeah, I'd need to see a benchmark (with the output lowercased so the test succeeds). However, I'd like to keep the simple version as simple as possible, so if you do anything further here, please submit a new PR that adds an `optimized.cs` version. That said, for an optimized version like the Go version you'd probably need to do a lot more, like reading in chunks, custom tokenization/lowercase, etc.

**Pull request closed without merging**
