### PR TITLE
faster c++

### PR DESCRIPTION
**Pull request by ncm**
Dunno if this counts as a "new submission".

But on my hardware (skylake) it now shows up as exactly as fast as the C code.
Curious about yours.

### CODE REVIEW

**Comment by benhoyt** [comment]
It doesn't count as a new submission :-), but on my machine it's no better, perhaps slightly worse. Before:

```
C             |   1.07 |      0.24 | 
C++           |   1.90 |      0.28 | optimized by Jussi P, Adev, Nathan M
```

After:

```
C             |   1.01 |      0.24 | 
C++           |   1.88 |      0.29 | optimized by Jussi P, Adev, Nathan M
```

Going to skip this one. Thanks again!

**Comment by ncm** [comment]
Getting more curious about what you are running these benchmarks on, and why the results are so different from mine.

**Comment by benhoyt** [comment]
Sure: it's a Dell XPS 15 laptop with an i7-6700HQ CPU (2.6GHz, 8 cores), 32GB RAM. I'm running Ubuntu Linux 20.04, kernel version 5.8.0.

**Comment by ncm** [comment]
That is stranger still, because I, also, am benchmarking on a 6700HQ, reporting 2.6 GHz.

Compiling with Gcc release 10.2.

**Comment by benhoyt** [comment]
Interesting coincidence! One difference here is our gcc version: I'm on 9.3.0, which came with `apt` on my Ubuntu version.

**Comment by ncm** [comment]
It seems to me like you should be worried to see so much variance in performance vs. an identical target CPU. Gcc 9 and gcc 10 code generators are not very different.

**Pull request closed without merging**
