### PR TITLE
Simple swift version

### PR DESCRIPTION
**Pull request by damuellen**
I have changed the code according to your wishes.

### CODE REVIEW

**Comment by mimi89999** [comment]
I think that you should squash your commits.

**Comment by damuellen** [comment]
> I think that you should squash your commits.



> 
> 
> I think that you should squash your commits.

I'm too stupid to use git, but I think you can squash the pull request when you merge it.

**Comment by benhoyt** [comment]
Thanks for this -- code looks nice! I'll merge as soon as I can benchmark it on my Linux machine (probably later today).

**Comment by benhoyt** [comment]
Thanks for the contribution!

**Pull request merged**
